package com.tal.gupao.mybatis.mapper;

import com.tal.gupao.mybatis.dao.bean.Author;
import com.tal.gupao.mybatis.dao.bean.AuthorExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface AuthorMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_author
     *
     * @mbggenerated
     */
    int countByExample(AuthorExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_author
     *
     * @mbggenerated
     */
    int deleteByExample(AuthorExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_author
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer authorId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_author
     *
     * @mbggenerated
     */
    int insert(Author record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_author
     *
     * @mbggenerated
     */
    int insertSelective(Author record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_author
     *
     * @mbggenerated
     */
    List<Author> selectByExample(AuthorExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_author
     *
     * @mbggenerated
     */
    Author selectByPrimaryKey(Integer authorId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_author
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") Author record, @Param("example") AuthorExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_author
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") Author record, @Param("example") AuthorExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_author
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(Author record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_author
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(Author record);
}