package com.tal.gupao.mybatis.dao.bean;

import java.util.Date;

public class Author {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_author.author_id
     *
     * @mbggenerated
     */
    private Integer authorId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_author.author_username
     *
     * @mbggenerated
     */
    private String authorUsername;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_author.author_password
     *
     * @mbggenerated
     */
    private String authorPassword;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_author.author_email
     *
     * @mbggenerated
     */
    private String authorEmail;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_author.author_bio
     *
     * @mbggenerated
     */
    private String authorBio;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_author.register_time
     *
     * @mbggenerated
     */
    private Date registerTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_author.author_id
     *
     * @return the value of tbl_author.author_id
     *
     * @mbggenerated
     */
    public Integer getAuthorId() {
        return authorId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_author.author_id
     *
     * @param authorId the value for tbl_author.author_id
     *
     * @mbggenerated
     */
    public void setAuthorId(Integer authorId) {
        this.authorId = authorId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_author.author_username
     *
     * @return the value of tbl_author.author_username
     *
     * @mbggenerated
     */
    public String getAuthorUsername() {
        return authorUsername;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_author.author_username
     *
     * @param authorUsername the value for tbl_author.author_username
     *
     * @mbggenerated
     */
    public void setAuthorUsername(String authorUsername) {
        this.authorUsername = authorUsername == null ? null : authorUsername.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_author.author_password
     *
     * @return the value of tbl_author.author_password
     *
     * @mbggenerated
     */
    public String getAuthorPassword() {
        return authorPassword;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_author.author_password
     *
     * @param authorPassword the value for tbl_author.author_password
     *
     * @mbggenerated
     */
    public void setAuthorPassword(String authorPassword) {
        this.authorPassword = authorPassword == null ? null : authorPassword.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_author.author_email
     *
     * @return the value of tbl_author.author_email
     *
     * @mbggenerated
     */
    public String getAuthorEmail() {
        return authorEmail;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_author.author_email
     *
     * @param authorEmail the value for tbl_author.author_email
     *
     * @mbggenerated
     */
    public void setAuthorEmail(String authorEmail) {
        this.authorEmail = authorEmail == null ? null : authorEmail.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_author.author_bio
     *
     * @return the value of tbl_author.author_bio
     *
     * @mbggenerated
     */
    public String getAuthorBio() {
        return authorBio;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_author.author_bio
     *
     * @param authorBio the value for tbl_author.author_bio
     *
     * @mbggenerated
     */
    public void setAuthorBio(String authorBio) {
        this.authorBio = authorBio == null ? null : authorBio.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_author.register_time
     *
     * @return the value of tbl_author.register_time
     *
     * @mbggenerated
     */
    public Date getRegisterTime() {
        return registerTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_author.register_time
     *
     * @param registerTime the value for tbl_author.register_time
     *
     * @mbggenerated
     */
    public void setRegisterTime(Date registerTime) {
        this.registerTime = registerTime;
    }
}