package com.tal.gupao.mybatis.dao.bean;

public class Blog {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_blog.blog_id
     *
     * @mbggenerated
     */
    private Integer blogId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_blog.blog_title
     *
     * @mbggenerated
     */
    private String blogTitle;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_blog.author_id
     *
     * @mbggenerated
     */
    private Integer authorId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_blog.blog_id
     *
     * @return the value of tbl_blog.blog_id
     *
     * @mbggenerated
     */
    public Integer getBlogId() {
        return blogId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_blog.blog_id
     *
     * @param blogId the value for tbl_blog.blog_id
     *
     * @mbggenerated
     */
    public void setBlogId(Integer blogId) {
        this.blogId = blogId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_blog.blog_title
     *
     * @return the value of tbl_blog.blog_title
     *
     * @mbggenerated
     */
    public String getBlogTitle() {
        return blogTitle;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_blog.blog_title
     *
     * @param blogTitle the value for tbl_blog.blog_title
     *
     * @mbggenerated
     */
    public void setBlogTitle(String blogTitle) {
        this.blogTitle = blogTitle == null ? null : blogTitle.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_blog.author_id
     *
     * @return the value of tbl_blog.author_id
     *
     * @mbggenerated
     */
    public Integer getAuthorId() {
        return authorId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_blog.author_id
     *
     * @param authorId the value for tbl_blog.author_id
     *
     * @mbggenerated
     */
    public void setAuthorId(Integer authorId) {
        this.authorId = authorId;
    }

    @Override
    public String toString() {
        return "Blog{" +
                "blogId=" + blogId +
                ", blogTitle='" + blogTitle + '\'' +
                ", authorId=" + authorId +
                '}';
    }
}