package com.tal.gupao.mybatis.dao.bean;

public class Comment {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tblcomment.ID
     *
     * @mbggenerated
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tblcomment.CONTENT
     *
     * @mbggenerated
     */
    private String content;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tblcomment.DESCRIPTION
     *
     * @mbggenerated
     */
    private String description;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tblcomment.COMMAND
     *
     * @mbggenerated
     */
    private String command;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tblcomment.ID
     *
     * @return the value of tblcomment.ID
     *
     * @mbggenerated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tblcomment.ID
     *
     * @param id the value for tblcomment.ID
     *
     * @mbggenerated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tblcomment.CONTENT
     *
     * @return the value of tblcomment.CONTENT
     *
     * @mbggenerated
     */
    public String getContent() {
        return content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tblcomment.CONTENT
     *
     * @param content the value for tblcomment.CONTENT
     *
     * @mbggenerated
     */
    public void setContent(String content) {
        this.content = content == null ? null : content.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tblcomment.DESCRIPTION
     *
     * @return the value of tblcomment.DESCRIPTION
     *
     * @mbggenerated
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tblcomment.DESCRIPTION
     *
     * @param description the value for tblcomment.DESCRIPTION
     *
     * @mbggenerated
     */
    public void setDescription(String description) {
        this.description = description == null ? null : description.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tblcomment.COMMAND
     *
     * @return the value of tblcomment.COMMAND
     *
     * @mbggenerated
     */
    public String getCommand() {
        return command;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tblcomment.COMMAND
     *
     * @param command the value for tblcomment.COMMAND
     *
     * @mbggenerated
     */
    public void setCommand(String command) {
        this.command = command == null ? null : command.trim();
    }
}