package com.tal.gupao.mybatis.dao.bean;

import java.util.Date;

public class Post {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_posts.post_id
     *
     * @mbggenerated
     */
    private Integer postId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_posts.post_subject
     *
     * @mbggenerated
     */
    private String postSubject;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_posts.blog_id
     *
     * @mbggenerated
     */
    private Integer blogId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_posts.createtime
     *
     * @mbggenerated
     */
    private Date createtime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_posts.post_body
     *
     * @mbggenerated
     */
    private String postBody;

    private Blog blog;

    public Blog getBlog() {
        return blog;
    }

    public void setBlog(Blog blog) {
        this.blog = blog;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_posts.post_id
     *
     * @return the value of tbl_posts.post_id
     *
     * @mbggenerated
     */
    public Integer getPostId() {
        return postId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_posts.post_id
     *
     * @param postId the value for tbl_posts.post_id
     *
     * @mbggenerated
     */
    public void setPostId(Integer postId) {
        this.postId = postId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_posts.post_subject
     *
     * @return the value of tbl_posts.post_subject
     *
     * @mbggenerated
     */
    public String getPostSubject() {
        return postSubject;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_posts.post_subject
     *
     * @param postSubject the value for tbl_posts.post_subject
     *
     * @mbggenerated
     */
    public void setPostSubject(String postSubject) {
        this.postSubject = postSubject == null ? null : postSubject.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_posts.blog_id
     *
     * @return the value of tbl_posts.blog_id
     *
     * @mbggenerated
     */
    public Integer getBlogId() {
        return blogId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_posts.blog_id
     *
     * @param blogId the value for tbl_posts.blog_id
     *
     * @mbggenerated
     */
    public void setBlogId(Integer blogId) {
        this.blogId = blogId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_posts.createtime
     *
     * @return the value of tbl_posts.createtime
     *
     * @mbggenerated
     */
    public Date getCreatetime() {
        return createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_posts.createtime
     *
     * @param createtime the value for tbl_posts.createtime
     *
     * @mbggenerated
     */
    public void setCreatetime(Date createtime) {
        this.createtime = createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_posts.post_body
     *
     * @return the value of tbl_posts.post_body
     *
     * @mbggenerated
     */
    public String getPostBody() {
        return postBody;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_posts.post_body
     *
     * @param postBody the value for tbl_posts.post_body
     *
     * @mbggenerated
     */
    public void setPostBody(String postBody) {
        this.postBody = postBody == null ? null : postBody.trim();
    }
}