package com.tal.gupao.mybatis.dao.bean;

import java.util.Date;

public class User {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_user.id
     *
     * @mbggenerated
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_user.name
     *
     * @mbggenerated
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_user.pwd
     *
     * @mbggenerated
     */
    private String pwd;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_user.status
     *
     * @mbggenerated
     */
    private String status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_user.icon
     *
     * @mbggenerated
     */
    private String icon;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_user.email
     *
     * @mbggenerated
     */
    private String email;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_user.createdate
     *
     * @mbggenerated
     */
    private Date createdate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_user.phone
     *
     * @mbggenerated
     */
    private String phone;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_user.salt2
     *
     * @mbggenerated
     */
    private String salt2;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_user.onlineStatus
     *
     * @mbggenerated
     */
    private String onlinestatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_user.lastUpdAcct
     *
     * @mbggenerated
     */
    private String lastupdacct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_user.lastUpdTime
     *
     * @mbggenerated
     */
    private Date lastupdtime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_user.note
     *
     * @mbggenerated
     */
    private String note;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_user.id
     *
     * @return the value of tbl_user.id
     *
     * @mbggenerated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_user.id
     *
     * @param id the value for tbl_user.id
     *
     * @mbggenerated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_user.name
     *
     * @return the value of tbl_user.name
     *
     * @mbggenerated
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_user.name
     *
     * @param name the value for tbl_user.name
     *
     * @mbggenerated
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_user.pwd
     *
     * @return the value of tbl_user.pwd
     *
     * @mbggenerated
     */
    public String getPwd() {
        return pwd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_user.pwd
     *
     * @param pwd the value for tbl_user.pwd
     *
     * @mbggenerated
     */
    public void setPwd(String pwd) {
        this.pwd = pwd == null ? null : pwd.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_user.status
     *
     * @return the value of tbl_user.status
     *
     * @mbggenerated
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_user.status
     *
     * @param status the value for tbl_user.status
     *
     * @mbggenerated
     */
    public void setStatus(String status) {
        this.status = status == null ? null : status.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_user.icon
     *
     * @return the value of tbl_user.icon
     *
     * @mbggenerated
     */
    public String getIcon() {
        return icon;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_user.icon
     *
     * @param icon the value for tbl_user.icon
     *
     * @mbggenerated
     */
    public void setIcon(String icon) {
        this.icon = icon == null ? null : icon.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_user.email
     *
     * @return the value of tbl_user.email
     *
     * @mbggenerated
     */
    public String getEmail() {
        return email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_user.email
     *
     * @param email the value for tbl_user.email
     *
     * @mbggenerated
     */
    public void setEmail(String email) {
        this.email = email == null ? null : email.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_user.createdate
     *
     * @return the value of tbl_user.createdate
     *
     * @mbggenerated
     */
    public Date getCreatedate() {
        return createdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_user.createdate
     *
     * @param createdate the value for tbl_user.createdate
     *
     * @mbggenerated
     */
    public void setCreatedate(Date createdate) {
        this.createdate = createdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_user.phone
     *
     * @return the value of tbl_user.phone
     *
     * @mbggenerated
     */
    public String getPhone() {
        return phone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_user.phone
     *
     * @param phone the value for tbl_user.phone
     *
     * @mbggenerated
     */
    public void setPhone(String phone) {
        this.phone = phone == null ? null : phone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_user.salt2
     *
     * @return the value of tbl_user.salt2
     *
     * @mbggenerated
     */
    public String getSalt2() {
        return salt2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_user.salt2
     *
     * @param salt2 the value for tbl_user.salt2
     *
     * @mbggenerated
     */
    public void setSalt2(String salt2) {
        this.salt2 = salt2 == null ? null : salt2.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_user.onlineStatus
     *
     * @return the value of tbl_user.onlineStatus
     *
     * @mbggenerated
     */
    public String getOnlinestatus() {
        return onlinestatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_user.onlineStatus
     *
     * @param onlinestatus the value for tbl_user.onlineStatus
     *
     * @mbggenerated
     */
    public void setOnlinestatus(String onlinestatus) {
        this.onlinestatus = onlinestatus == null ? null : onlinestatus.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_user.lastUpdAcct
     *
     * @return the value of tbl_user.lastUpdAcct
     *
     * @mbggenerated
     */
    public String getLastupdacct() {
        return lastupdacct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_user.lastUpdAcct
     *
     * @param lastupdacct the value for tbl_user.lastUpdAcct
     *
     * @mbggenerated
     */
    public void setLastupdacct(String lastupdacct) {
        this.lastupdacct = lastupdacct == null ? null : lastupdacct.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_user.lastUpdTime
     *
     * @return the value of tbl_user.lastUpdTime
     *
     * @mbggenerated
     */
    public Date getLastupdtime() {
        return lastupdtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_user.lastUpdTime
     *
     * @param lastupdtime the value for tbl_user.lastUpdTime
     *
     * @mbggenerated
     */
    public void setLastupdtime(Date lastupdtime) {
        this.lastupdtime = lastupdtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_user.note
     *
     * @return the value of tbl_user.note
     *
     * @mbggenerated
     */
    public String getNote() {
        return note;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_user.note
     *
     * @param note the value for tbl_user.note
     *
     * @mbggenerated
     */
    public void setNote(String note) {
        this.note = note == null ? null : note.trim();
    }
}